[tool.poetry]
name = "eggm_io"
version = "0.1.0"
description = ""
authors = ["Vas <vas@va.va>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
fastapi = "^0.115.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.35"}
asyncpg = "^0.29.0"
alembic = "^1.13.3"
black = "^24.8.0"
pydantic-settings = "^2.5.2"
typer = "^0.12.5"
uvicorn = "^0.31.0"
pydantic = "^2.9.2"
orjson = "^3.10.7"
pytest = "^8.3.3"
pytest-asyncio = "^0.24.0"
typing-extensions = "^4.12.2"
dishka = "^1.4.2"
httpx = "^0.28.1"
pytz = "^2025.1"
taskiq-redis = "^1.0.3"
faststream = "^0.5.39"
aiokafka = "^0.12.0"
uuid6 = "^2024.7.10"
aiohttp = "^3.13.3"
elasticsearch = "^9.2.1"
aiogram = "^3.24.0"
openai = "^2.14.0"
langgraph = "^1.0.5"
langgraph-supervisor = "^0.0.31"
langchain-openai = "^1.1.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
asyncio_mode = "auto"

